INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`)
VALUES
-- Existing item data
    ('poor_bear_pelt', 'Poor Bear pelt', 5, 1, 'item_standard', 0),
    ('good_bear_pelt', 'Good Bear pelt', 5, 1, 'item_standard', 0),
    ('perfect_bear_pelt', 'Perfect Bear pelt', 5, 1, 'item_standard', 0),
    ('poor_bighornram_pelt', 'Poor Big Horn Ram pelt', 5, 1, 'item_standard', 0),
    ('good_bighornram_pelt', 'Good Big Horn Ram pelt', 5, 1, 'item_standard', 0),
    ('perfect_bighornram_pelt', 'Perfect Big Horn Ram pelt', 5, 1, 'item_standard', 0),
    ('poor_boar_pelt', 'Poor Boar pelt', 5, 1, 'item_standard', 0),
    ('perfect_boar_pelt', 'Perfect Boar pelt', 5, 1, 'item_standard', 0),
    ('poor_buck_pelt', 'Poor Buck pelt', 5, 1, 'item_standard', 0),
    ('good_buck_pelt', 'Good Buck pelt', 5, 1, 'item_standard', 0),
    ('perfect_buck_pelt', 'Perfect Buck pelt', 5, 1, 'item_standard', 0),
    ('poor_bison_pelt', 'Poor Bison pelt', 5, 1, 'item_standard', 0),
    ('good_bison_pelt', 'Good Bison pelt', 5, 1, 'item_standard', 0),
    ('perfect_bison_pelt', 'Perfect Bison pelt', 5, 1, 'item_standard', 0),
    ('poor_deer_pelt', 'Poor Deer pelt', 5, 1, 'item_standard', 0),
    ('good_deer_pelt', 'Good Deer pelt', 5, 1, 'item_standard', 0),
    ('perfect_deer_pelt', 'Perfect Deer pelt', 5, 1, 'item_standard', 0),
    ('poor_elk_pelt', 'Poor Elk pelt', 5, 1, 'item_standard', 0),
    ('good_elk_pelt', 'Good Elk pelt', 5, 1, 'item_standard', 0),
    ('perfect_elk_pelt', 'Perfect Elk pelt', 5, 1, 'item_standard', 0),
    ('poor_coyote_pelt', 'Poor Coyote pelt', 5, 1, 'item_standard', 0),
    ('good_coyote_pelt', 'Good Coyote pelt', 5, 1, 'item_standard', 0),
    ('perfect_coyote_pelt', 'Perfect Coyote pelt', 5, 1, 'item_standard', 0),
    ('poor_greywolf_pelt', 'Poor Grey Wolf pelt', 5, 1, 'item_standard', 0),
    ('good_greywolf_pelt', 'Good Grey Wolf pelt', 5, 1, 'item_standard', 0),
    ('perfect_greywolf_pelt', 'Perfect Grey Wolf pelt', 5, 1, 'item_standard', 0),
    ('poor_redfox_pelt', 'Poor Red Fox pelt', 5, 1, 'item_standard', 0),
    ('good_redfox_pelt', 'Good Red Fox pelt', 5, 1, 'item_standard', 0),
    ('perfect_redfox_pelt', 'Perfect Redfox pelt', 5, 1, 'item_standard', 0),
    ('poor_pronghorn_pelt', 'Poor Pronghorn pelt', 5, 1, 'item_standard', 0),
    ('good_pronghorn_pelt', 'Good Pronghorn pelt', 5, 1, 'item_standard', 0),
    ('perfect_pronghorn_pelt', 'Perfect Pronghorn pelt', 5, 1, 'item_standard', 0),
    ('poor_cougar_pelt', 'Poor Cougar pelt', 5, 1, 'item_standard', 0),
    ('good_cougar_pelt', 'Good Cougar pelt', 5, 1, 'item_standard', 0),
    ('perfect_cougar_pelt', 'Perfect Cougar pelt', 5, 1, 'item_standard', 0),
    ('poor_panther_pelt', 'Poor Panther pelt', 5, 1, 'item_standard', 0),
    ('good_panther_pelt', 'Good Panther pelt', 5, 1, 'item_standard', 0),
    ('perfect_panther_pelt', 'Perfect Panther pelt', 5, 1, 'item_standard', 0),
    ('poor_beaver_pelt', 'Poor Beaver pelt', 5, 1, 'item_standard', 0),
    ('good_beaver_pelt', 'Good Beaver pelt', 5, 1, 'item_standard', 0),
    ('perfect_beaver_pelt', 'Perfect Beaver pelt', 5, 1, 'item_standard', 0),
    ('poor_aligator_pelt', 'Poor Aligator pelt', 5, 1, 'item_standard', 0),
    ('good_aligator_pelt', 'Good Aligator pelt', 5, 1, 'item_standard', 0),
    ('perfect_aligator_pelt', 'Perfect Aligator pelt', 5, 1, 'item_standard', 0),
    ('poor_moose_pelt', 'Poor Moose pelt', 5, 1, 'item_standard', 0),
    ('good_moose_pelt', 'Good Moose pelt', 5, 1, 'item_standard', 0),
    ('perfect_moose_pelt', 'Perfect Moose pelt', 5, 1, 'item_standard', 0),
    ('poor_bull_pelt', 'Poor Bull pelt', 5, 1, 'item_standard', 0),
    ('good_bull_pelt', 'Good Bull pelt', 5, 1, 'item_standard', 0),
    ('perfect_bull_pelt', 'Perfect Bull pelt', 5, 1, 'item_standard', 0);
